global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-microsoft-lync
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  reporting: true
tests:
  defaults:
    parameter_input: Lync_2013_Master.json
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    template_file: Lync_2013_Master.template
  withedge:
    parameter_input: Lync_2013_Master_with_Edge.json
    regions:
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    template_file: Lync_2013_Master.template
